---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap caskroom/fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: tap homebrew/core
  homebrew_tap: tap=homebrew/core state=present

- name: install developer brew applications
  homebrew: name={{ item }} state=latest
  with_items:
    - git
    - sift
    - wget
    - htop-osx
    - tmux
    - tree
    - zsh
